global:
  resolve_timeout: 5m

route:

  receiver: "alerta"
  group_by: ["alertname", "service", "job", "instance"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:

  - name: alerta
    webhook_configs:
      - url: "http://alerta:8080/webhooks/prometheus"
        send_resolved: true
